services:
  postgres:
    image: postgres:14
    container_name: users-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: otus_users_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - users-net
    ports:
      - "5432:5432"

  users-api:
    image: yapasha/users-api:latest
    container_name: users-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - users-net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  users-net:

